export const ROUTES = {
  home: "/",
  shop: "/shop",
  categories: "/categories",
  category: (slug: string) => `/categories/${slug}`,
  product: (slug: string) => `/product/${slug}`,
  about: "/about",
  contact: "/contact",
  faq: "/faq",
  research: "/research",
  shipping: "/shipping",
  privacy: "/privacy",
  terms: "/terms",
  returns: "/returns",
  cart: "/cart",
  checkout: "/checkout",
  orderSuccess: (orderNumber: string) => `/order-success/${orderNumber}`,
  search: "/search",
  articles: "/articles",
  article: (slug: string) => `/articles/${slug}`,
} as const;
