export const ROUTES = {
  home: "/",
  shop: "/shop",
  categories: "/categories",
  category: (slug: string) => `/categories/${slug}`,
  product: (slug: string) => `/product/${slug}`,
  about: "/about",
  contact: "/contact",
  faq: "/faq",
  research: "/research",
  shipping: "/shipping",
  privacy: "/privacy",
  terms: "/terms",
  returns: "/returns",
  cart: "/cart",
  checkout: "/checkout",
  orderSuccess: (orderNumber: string) => `/order-success/${orderNumber}`,
  search: "/search",
  articles: "/blog",
  article: (slug: string) => `/blog/${slug}`,
  blog: "/blog",
  blogPost: (slug: string) => `/blog/${slug}`,
  reviews: "/reviews",
  qualityDocumentation: "/quality-documentation",
  login: "/login",
  signup: "/signup",
  account: "/account",
} as const;
